name: 'lvCICD'
author: 'LV-APT'
description: 'CICD Action used for LabVIEW Users'
branding:
  icon: 'tool'
  color: 'green'

inputs:
  lvCICD:
    description: 'CommandLine'
    required: false
    default: LabVIEWCLI -OperationName RunVI -VIPath "${{ github.action_path }}\lvapt-CICD.vi"
  LabVIEW_Version:
    description: 'LabVIEW Version Used'
    required: false
    default: "2019"
  PortNum:
    description: 'LabVIEW Version Used'
    required: false
    default: "3364"
  Operation:
    description: 'The operation of lvCICD'
    required: false
    default: 'lvecho'

runs:
  using: "composite"

  steps:
    - name: "Checkout lvCICD Action"
      uses: actions/checkout@v2.4.2

    - name: "Set lvCICD Script Env Variable"
      run:
        ${{ github.action_path }}\SetGithubEnvVariable.ps1 lvCICD abcdef
      shell: powershell

    - name: "Show working dir"
      run: pwd
      shell: powershell

    - run: echo "{PortNum}={${{ github.action_path }}\ViServerPort.ps1}" >> $GITHUB_ENV
      shell: powershell

#  echo "{lvCICD}={LabVIEWCLI -OperationName RunVI -VIPath "${{ github.action_path }}\lvapt-CICD.vi" -LabVIEWPath "C:\Program Files (x86)\National Instruments\LabVIEW 2019\LabVIEW.exe" -PortNumber 3364}" >> $GITHUB_ENV
    - name: "Test Environment"
      run: ${{ INPUT_LVCICD }} -LabVIEWPath "C:\Program Files (x86)\National Instruments\LabVIEW ${{ INPUT_LABVIEW_VERSION }}\LabVIEW.exe" -PortNumber ${{ INPUT_PORTNUM }} lvEcho "line1" "line2" "line3"
      shell: powershell