name: "lvCICD"
author: "LV-APT"
description: "CICD Action used for LabVIEW Users"
branding:
  icon: "tool"
  color: "green"

inputs:
  LabVIEW_Version:
    description: "LabVIEW Version Used"
    required: false
    default: "2019"
  Architecture:
    description: "32bit/64bit Verion of LabVIEW Used"
    required: false
    default: "x86"
  Operation:
    description: "The operation of lvCICD"
    required: false
    default: "lvecho"
  Parameter1:
    description: "Parameter1 of lvCICD"
    required: false
    default: ""
  Parameter2:
    description: "Parameter2 of lvCICD"
    required: false
    default: ""
  Parameter3:
    description: "Parameter3 of lvCICD"
    required: false
    default: ""
  Parameter4:
    description: "Parameter4 of lvCICD"
    required: false
    default: ""
  Parameter5:
    description: "Parameter5 of lvCICD"
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: "Checkout lvCICD Action"
      uses: actions/checkout@v2.4.2

    # - name: "Show working dir"
    #   run: pwd
    #   shell: powershell

    - name: "Run Scripts"
      run:
        $LabVIEWExePath = ${{ github.action_path }}\LabVIEW_exe_path.ps1 ${{ inputs.LabVIEW_Version }} ${{ inputs.Architecture }};
        $PortNum = ${{ github.action_path }}\ViServerPort.ps1 ${{ inputs.LabVIEW_Version }};
        LabVIEWCLI -OperationName RunVI `
          -VIPath "${{ github.action_path }}\LabVIEW-Adapter\lvCICD.vi" `
          -LogFilePath ${{ github.action_path }}\lVCLI.log `
          -LogToConsole True `
          -LabVIEWPath $LabVIEWExePath `
          -PortNumber $PortNum `
          ${{ inputs.Operation }} `
          ${{ inputs.Parameter1 }} ${{ inputs.Parameter2 }} ${{ inputs.Parameter3 }} ${{ inputs.Parameter4 }} ${{ inputs.Parameter5 }}
      shell: powershell
