name: 'lvCICD'
author: 'Yao'
description: 'CICD Action used for LabVIEW Users'

runs:
  using: "composite"

  steps:
    - name: "Checkout lvCICD Action"
      uses: actions/checkout@v2.4.2

    - run: pwd
      shell: powershell

    - run: .\ViServerPort.ps1
      shell: powershell