name: 'lvCICD'
author: 'LV-APT'
description: 'CICD Action used for LabVIEW Users'
branding:
  icon: 'tool'
  color: 'green'

inputs:
  Operation:
    description: 'The operation of lvCICD'
    required: false
    default: 'lvecho'

runs:
  using: "composite"

  steps:
    - name: "Checkout lvCICD Action"
      uses: actions/checkout@v2.4.2

    - name: "Show working dir"
      run: pwd
      shell: powershell

    - run: .\ViServerPort.ps1
      shell: powershell
