name: 'lvCICD'
author: 'Yao'
description: 'CICD Action used for LabVIEW Users'

runs:
  using: "composite"

  steps:
    - run: pwd
      shell: powershell

    - run: .\ViServerPort.ps1
      shell: powershell