name: 'lvCICD'
author: 'LV-APT'
description: 'CICD Action used for LabVIEW Users'
branding:
  icon: 'tool'
  color: 'green'

inputs:
  Operation:
    description: 'The operation of lvCICD'
    required: false
    default: 'lvecho'

runs:
  using: "composite"

  steps:
    - name: "Checkout lvCICD Action"
      uses: actions/checkout@v2.4.2

    - name: "Show working dir"
      run: pwd
      shell: powershell

    - run: ${{ github.action_path }}\ViServerPort.ps1
      shell: powershell

    - name: "Test Environment"
      env:
        lvCICD: LabVIEWCLI -OperationName RunVI -VIPath "${{ github.action_path }}\lvapt-CICD.vi" -LabVIEWPath "C:\Program Files (x86)\National Instruments\LabVIEW 2019\LabVIEW.exe" -PortNumber 3364
      run: ${{ env.lvCICD }} lvEcho "line1" "line2" "line3"
      shell: powershell