name: Sync With AZDO

# Controls when the workflow will run
on: [push,workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  SyncWithAZDO:
    # The type of runner that the job will run on
    name: SyncWithAZDO
    runs-on: [linux]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

