name: Sync With AZDO

# Controls when the workflow will run
on:
  push:
    branches:
      - main

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  SyncWithAZDO:
    # The type of runner that the job will run on
    name: SyncWithAZDO
    runs-on: [ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          repository: ${{ github.repository }}
          ref: main

      - name: Git Add Azure Repo URL
        run: git remote set-url origin https://ni@dev.azure.com/ni/GlobalSupport/_git/lvCICD

      - name: Show Git remote
        run: git remote -v

      - name: push main branch to AZDO
        run:
          git push https://${{ secrets.AZDO_LVCICD_PAT_TOKEN }}@dev.azure.com/ni/GlobalSupport/_git/lvCICD


