name: Test Build Envrionment

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 16 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  lvaptCICD: LabVIEWCLI -OperationName RunVI -VIPath "${{ github.workspace }}\lvapt-CICD.vi" -LabVIEWPath "C:\Program Files (x86)\National Instruments\LabVIEW 2019\LabVIEW.exe"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  lvCICD:
    # The type of runner that the job will run on
    name: lvCICD Preparation
    runs-on: [self-hosted]

    outputs:
      portNum: ${{ steps.ViServer.outputs.portNum }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: CloneRepo
        uses: actions/checkout@v2

      - name: GetVIPortNum
        id: ViServer
        run: ${{ github.workspace }}/ViServerPort.ps1

      - name: BuildCommands
        run:
          echo ${{ steps.ViServer.outputs.portNum }}
          echo "(test=abc)" >> $GITHUB_ENV

      - name: TestEnvironment
        run:
          ${{ env.lvaptCICD }} -PortNumber ${{ steps.ViServer.outputs.portNum}} lvEcho "line1" "line2" "line3"

  EchoResults:
    # The type of runner that the job will run on
    runs-on: [self-hosted]
    needs: lvCICD

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: EchoResults
        run:
          echo ${{ env.lvaptCICD }}
          echo ${{ needs.lvCICD.outputs.portNum }}
